### ISSUE TITLE
 Solthiruthi - framework - Trie data structure - pickle capability

### ISSUE THREAD

**Issue by arcturusannamalai** [arcturusannamalai/open-tamil#37]
Following 'Solthiruthi - framework - Trie data structure' issue #36 we need to,
1. add pickle capability to save index to disk
2. load pickle file from disk into in-memory index
3. add unit  tests

**Comment by arcturusannamalai** [comment]
Arulalan did you get a chance to review this task ? Please let me know.

**Comment by arulalant** [comment]
Sorry, I couldn't get much free time.
I will be out of India for next 15 days to present my M.Tech work in
Conference, Singapore.
I will come back and look at this after mid-August.
Thanks.

On 30 July 2015 at 10:04, Muthiah Annamalai <notifications@github.com>
wrote:

> Arulalan did you get a chance to review this task ? Please let me know.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arcturusannamalai/open-tamil/issues/37#issuecomment-126179570>
> .
>



-- 
Regards,
Arulalan.T
Project Associate
Centre for Atmospheric Sciences
Indian Institute of Technology Delhi

My Experiments In Gnu/Linux !  : http://tuxcoder.wordpress.com

**Comment by arcturusannamalai** [comment]
Goodluck, Arulalan! Looking forward to having your contributions in future :-)

**Comment by arcturusannamalai** [comment]
Simple task from references at https://docs.python.org/2/library/pickle.html
```
import pickle

data1 = {'a': [1, 2.0, 3, 4+6j],
         'b': ('string', u'Unicode string'),
         'c': None}

selfref_list = [1, 2, 3]
selfref_list.append(selfref_list)

output = open('data.pkl', 'wb')

# Pickle dictionary using protocol 0.
pickle.dump(data1, output)

# Pickle the list using the highest protocol available.
pickle.dump(selfref_list, output, -1)

output.close()
```

The following example reads the resulting pickled data. When reading a pickle-containing file, you should open the file in binary mode because you can’t be sure if the ASCII or binary format was used.

```
import pprint, pickle

pkl_file = open('data.pkl', 'rb')

data1 = pickle.load(pkl_file)
pprint.pprint(data1)

data2 = pickle.load(pkl_file)
pprint.pprint(data2)

pkl_file.close()
```
