### ISSUE TITLE
get_letters_elementary : split word -> letters reducing uyirmei

### ISSUE THREAD

**Issue by arcturusannamalai** [arcturusannamalai/open-tamil#62]
1. get_letters_elementary : split word -> letters reducing uyirmei
This routine is useful in mapping the letters to santhi.

e.g. get_letters_elementary(u'கழுதை') -> க் அ ழ் உ த் ஐ

**Comment by arulalant** [comment]
It seems duplicate. 
Already I added that function "splitMeiUyir" and "joinMeiUyir" in end of the module "tamil.utf8". These function I used in santhirules.py...

**Comment by arcturusannamalai** [comment]
Good point, Arulalan. It does have some overlap but writing the  code with yield, and code size in my approach is much smaller. 
I propose we keep both the functions.
