### ISSUE TITLE
open-tamil நேரம் படிக்கும் கெடியாரம்

### ISSUE THREAD

**Issue by arcturusannamalai** [arcturusannamalai/open-tamil#71]
நேரம் படிக்கும் கெடியாரம் ஒன்றை எப்படி உருவாக்கலாம்?

இப்போது கீழே உள்ள அனைத்து சொற்களுக்கும் ஒலி வடிவில் தயார் செய்ய வேண்டும்.

```
    units = (u’பூஜ்ஜியம்’, u’ஒன்று’, u’இரண்டு’, u’மூன்று’, u’நான்கு’, u’ஐந்து’, u’ஆறு’, u’ஏழு’, u’எட்டு’, u’ஒன்பது’, u’பத்து’) # 0-10
    teens = (u’பதினொன்று’, u’ பனிரண்டு’, u’பதிமூன்று’, u’பதினான்கு’, u’பதினைந்து’,u’பதினாறு’, u’பதினேழு’, u’பதினெட்டு’, u’பத்தொன்பது’) # 11-19
    tens = (u’பத்து’, u’இருபது’, u’முப்பது’, u’நாற்பது’, u’ஐம்பது’,u’அறுபது’, u’எழுபது’, u’எண்பது’, u’தொன்னூறு’) # 10-90
    tens_suffix = (u’இருபத்தி’, u’முப்பத்தி’, u’நாற்பத்தி’, u’ஐம்பத்தி’, u’அறுபத்தி’, u’எழுபத்தி’, u’எண்பத்தி’, u’தொன்னூற்றி’) # 10+-90+
    hundreds = ( u’நூறு’, u’இருநூறு’, u’முன்னூறு’, u’நாநூறு’,u’ஐநூறு’, u’அறுநூறு’, u’எழுநூறு’, u’எண்ணூறு’, u’தொள்ளாயிரம்’) #100 – 900
    hundreds_suffix = (u’நூற்றி’, u’இருநூற்றி’, u’முன்னூற்று’, u’நாநூற்று’, u’ஐநூற்று’, u’அறுநூற்று’, u’எழுநூற்று’, u’எண்ணூற்று’,u’தொள்ளாயிரத்து’) #100+ – 900+
    one_thousand_prefix = u’ஓர்’
    thousands = (u’ஆயிரம்’,u’ஆயிரத்தி’)
    one_prefix = u’ஒரு’
    lakh = (u’இலட்சம்’,u’இலட்சத்தி’)
    crore = (u’கோடி’,u’கோடியே’)
```
This is a list of 63 words,
```
00) பூஜ்ஜியம்
01) ஒன்று
02) இரண்டு
03) மூன்று
04) நான்கு
05) ஐந்து
06) ஆறு
07) ஏழு
08) எட்டு
09) ஒன்பது
10) பத்து
11) பதினொன்று
12)  பனிரண்டு
13) பதிமூன்று
14) பதினான்கு
15) பதினைந்து
16) பதினாறு
17) பதினேழு
18) பதினெட்டு
19) பத்தொன்பது
20) பத்து
21) இருபது
22) முப்பது
23) நாற்பது
24) ஐம்பது
25) அறுபது
26) எழுபது
27) எண்பது
28) தொன்னூறு
29) இருபத்தி
30) முப்பத்தி
31) நாற்பத்தி
32) ஐம்பத்தி
33) அறுபத்தி
34) எழுபத்தி
35) எண்பத்தி
36) தொன்னூற்றி
37) நூறு
38) இருநூறு
39) முன்னூறு
40) நாநூறு
41) ஐநூறு
42) அறுநூறு
43) எழுநூறு
44) எண்ணூறு
45) தொள்ளாயிரம்
46) நூற்றி
47) இருநூற்றி
48) முன்னூற்று
49) நாநூற்று
50) ஐநூற்று
51) அறுநூற்று
52) எழுநூற்று
53) எண்ணூற்று
54) தொள்ளாயிரத்து
55) ஓர்
56) ஆயிரம்
57) ஆயிரத்தி
58) ஒரு
59) இலட்சம்
60) இலட்சத்தி
61) கோடி
62) கோடியே
```
Ref: https://ezhillang.wordpress.com/2015/06/28/%E0%AE%A8%E0%AF%87%E0%AE%B0%E0%AE%AE%E0%AF%8D-%E0%AE%AA%E0%AE%9F%E0%AE%BF%E0%AE%95%E0%AF%8D%E0%AE%95%E0%AF%81%E0%AE%AE%E0%AF%8D-%E0%AE%95%E0%AF%86%E0%AE%9F%E0%AE%BF%E0%AE%AF%E0%AE%BE%E0%AE%B0%E0%AE%AE/

**Comment by msathia** [comment]
Do you want wav file? for each of those 62 words and uploaded here.

**Comment by arcturusannamalai** [comment]
Sure, 63 words are good but you may send 1 file too; I recorded a single AMR file on my phone - and it lasts 1m 25s. We can chop up the file later. 

If you also can get a female voice it will be good. Any contribution is welcome!

**Comment by priyacst** [comment]
I will give the female voice.

**Comment by arcturusannamalai** [comment]
Hello @priyacst thanks for volunteering.
1. You can use the tool, audacity (install from http://sourceforge.net/projects/audacity/)
2. You can record all the 63 words at a time; this will take 1m 30s. 
    Please record at 44.1kHz resolution, stereo, if possible.
3. Then you can copy the sound sections into its own WAV file.
4. Repeat step 3, for all 63 words. 
5. Save the file names in the pattern, 0 -> units_0.wav, முன்னூறு -> hundreds_2.wav

If you are not able to edit to 63 files, please just share the WAV or MP3 file upto step 2, and I can do the post-processing.

Thanks.
-Muthu

**Comment by priyacst** [comment]
Hi,
I have attached the audio file as mp3.

On Wed, Jul 1, 2015 at 7:18 AM, Muthiah Annamalai <notifications@github.com>
wrote:

> Hello @priyacst <https://github.com/priyacst> thanks for volunteering.
> 1. You can use the tool, audacity (install from
> http://sourceforge.net/projects/audacity/)
> 2. You can record all the 63 words at a time; this will take 1m 30s.
> Please record at 44.1kHz resolution, stereo, if possible.
> 3. Then you can copy the sound sections into its own WAV file.
> 4. Repeat step 3, for all 63 words.
> 5. Save the file names in the pattern, 0 -> units_0.wav, முன்னூறு ->
> hundreds_2.wav
>
> If you are not able to edit to 63 files, please just share the WAV or MP3
> file upto step 2, and I can do the post-processing.
>
> Thanks.
> -Muthu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/arcturusannamalai/open-tamil/issues/71#issuecomment-117390465>
> .
>



-- 
with Regards,
K. Priya

**Comment by arcturusannamalai** [comment]
Hello @priyacst  I did not get your email attachment; 
Would you be able to send me the attachment via email to ezhillang@gmail.com ? 

Thank you for your contribution.

**Comment by arcturusannamalai** [comment]
Add voice information from @priyacst after processing from Audible to get 63 equalized WAV files from the source  MP3.
