### ISSUE TITLE
Solthiruthi - framework - canned dictionary

### ISSUE THREAD

**Issue by arcturusannamalai** [arcturusannamalai/open-tamil#74]
Provide way to use TamilVU dictionary in form of Trie with a easy builder/factory API.
e.g.

```
    agarathi,size = DictionaryBuilder.create(TamilVU)
    agarathi.isWord( word ) #returns True or False
```

**Comment by velsubra** [comment]
Friends,
is it possible for me to  get list of Tamil root nouns and verbs along with
its English word?
Thanks
Vel

On Thu, Jul 23, 2015 at 7:40 PM, Muthiah Annamalai <notifications@github.com

**Comment by arcturusannamalai** [comment]
Hello Vel/@velsubra I don't have this list yet. I only have a collection of words, that too requires cleanup.
I don't think there is a published list of root words, but @tshrinivasan has done lot of work in researching this aspect for his Sorkandu project.

This would be very useful for the spell checker project also.

Thanks,
-Muthu
